### ISSUE TITLE
[作业2] - 实现第一个页面

### ISSUE THREAD

**Issue by haiyuanhe** [wxy1995/cloudwiz-train#2]
1. 使用 mock server 已经准备好的数据. 
2. 按照墨刀的原型图来实现
    1. https://free.modao.cc/app/VxfK6AQJgVQ9DB3M4AFQdf6iti5Kv2E

**Comment by haiyuanhe** [comment]
@wxy1995 准备 [指标管理] api 说明

**Comment by wxy1995** [comment]
[api 说明](https://github.com/wxy1995/cloudwiz-train/wiki/CDMB-%E6%8C%87%E6%A0%87%E7%AE%A1%E7%90%86)
